# Generated by Django 5.0.4 on 2024-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_review_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='defult.jpg', null=True, upload_to=''),
        ),
    ]
